config/routes.rb
Rails.application.routes.draw do
  # resources :boards do
  #   resources :posts, only: [:index, :new, :create]
  # end
  # resources :posts, except: [:index, :new, :create]

  resources :boards do
    resources :posts, shallow: true
  end
  
  root "boards#index"
  get "/about", to: "pages#about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord

  acts_as_paranoid
  has_many :posts
  validates :title, :intro, presence: true, length: {minimum: 2}
  #It can not be submited, If the column of title is blank.
  # default_scope { where(deleted_at: nil) }

  # def destroy
  #   @board.update(deleted_at: Time.now)
  # end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :board

  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found
    render file: '/public/404.html', status: 404
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController

  before_action :find_board, only: [:show, :edit, :destroy, :update]

  def index
    # @boards = Board.where(deleted_at: nil) #如果不加區域變數的話，查完之後結果就會被蒸發沒辦法被取用，因為下面的update方法是使用軟刪除的方式，所以不能使用all方法要使用where去篩選deleted_at欄位是空的
    @boards = Board.all
  end

  def new
    @board = Board.new
  end

  def show
  end

  def edit
  end

  #where找出來的東西都會用陣列包起來，要取用裡面的值需要在下.first比find方法多麻煩一點，取出的形式為 [1]
  #find and find_by 只會找到一筆資料 取出的形式為 1，另外find只能接id，find_by可以換成其他params

  def create
    @board = Board.new(board_params) #HTTP 沒有狀態所以需要在這邊在下一次new後面塞入params接住String

    if @board.save
      #flash[:notice] = 'Board Created !' 下面是二合一版本
      redirect_to boards_path, notice: 'Board Created !' #好處是只要在routes.rb改變首頁之後全站的root_path就會被套用
    else
      render :new  #借new的頁面重新渲染
    end

  end

  def update
    if @board.update(board_params)
      redirect_to boards_path, notice: 'Board Updated !'
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    # @board.update(deleted_at: Time.now, abc: false)
    redirect_to boards_path, notice: 'Board Deleted !'
  end

  

  private
#清洗資料的方法
  def board_params
    params.require(:board).permit(:title, :intro) #寫入資料庫的資料需要清過清洗確保不會被上一個頁面的有心人士塞入奇怪的資料
  end

  def find_board
    @board = Board.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_board, only: [:new, :create]
  def new
    @post = @board.posts.new
    #@post = Post.new
  end

  def create
    @post = @board.posts.new(post_params)

    if @post.save
      redirect_to @board, notice: '創建成功'
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end

  def find_board
    @board = Board.find(params[:board_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/boards/_form.html.erb
<% if board.errors.any? %>
  <ul>
    <% board.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_for(board) do |form| %>

<div>
  <%= form.label :title, '看板名稱' %>
  <%= form.text_field :title %>
</div>

<div>
  <%= form.label :intro, '看板說明' %>
  <%= form.text_area :intro %>
</div>

<%= form.submit '送出' %>
<% end %>

app/views/boards/edit.html.erb
<h1>編輯看板</h1>

<%= render 'form', board: @board%>

app/views/boards/index.html.erb

<h1>看板</h1>

<%= link_to '新增看板', new_board_path %>

<ul>
  <% @boards.each do |board| %>
    <li>
      <%= link_to board.title, board_path(board.id) %>
      <%= link_to '編輯', edit_board_path(board.id) %>
      <%= link_to '刪除', board_path(board.id), method: 'delete', data: {confirm: 'are you sure?'} %>
    </li>
  <% end %>
</ul>

app/views/boards/new.html.erb
<h1>新增看板</h1>

<%= render 'form', board: @board %>




app/views/boards/show.html.erb
<%= notice %>
<h1><%= @board.title %></h1>



<%= link_to '新增文章', new_board_post_path(@board) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ppt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= notice %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Hey! guys</h1>

app/views/pages/index.html.erb
<h1>Hello World!!!</h1>

app/views/posts/new.html.erb
<h1>Add Post</h1>

<% if @post.errors.any? %>
<ul>
  <% @post.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with(model: @post, url: board_posts_path) do |form| %>
<div>
  <%= form.label :title, '標題' %>
  <%= form.text_field :title %>
</div>
<div>
  <%= form.label :content, '內文' %>
  <%= form.text_area :content %>
</div>
<%= form.submit %>


<% end %>